### ISSUE TITLE
Can't compile package : Cost does not name a type

### ISSUE THREAD

**Issue by JimmyDaSilva** [davetcoleman/ompl_visual_tools#1]
I'm having issues to compile this package.
I'm running on hydro and Ubuntu 12.04.
I get the following error : 

[ 66%] Building CXX object ompl_rviz_viewer/CMakeFiles/ompl_rviz_viewer.dir/src/ompl_rviz_viewer.cpp.o
In file included from /home/jimmy/catkin_ws/src/ompl_rviz_viewer/include/ompl_rviz_viewer/ompl_rviz_viewer.h:53:0,
                 from /home/jimmy/catkin_ws/src/ompl_rviz_viewer/src/ompl_rviz_viewer.cpp:40:
/home/jimmy/catkin_ws/src/ompl_rviz_viewer/include/ompl_rviz_viewer/costs/cost_map_2d_optimization_objective.h:96:13: error: ‘Cost’ does not name a type
/home/jimmy/catkin_ws/src/ompl_rviz_viewer/include/ompl_rviz_viewer/costs/cost_map_2d_optimization_objective.h:103:5: error: ‘Cost’ in namespace ‘ompl::base’ does not name a type
make[2]: **\* [ompl_rviz_viewer/CMakeFiles/ompl_rviz_viewer.dir/src/ompl_rviz_viewer.cpp.o] Error 1
make[1]: **\* [ompl_rviz_viewer/CMakeFiles/ompl_rviz_viewer.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

**Comment by davetcoleman** [comment]
I assume you are running the latest source? I'll test later today.

**Comment by JimmyDaSilva** [comment]
Yes I am. Thank you

**Comment by davetcoleman** [comment]
I just merged a lot of changes into the hydro-devel branch. ompl_rviz_viewer now depends on [moveit_visual_tools](https://github.com/davetcoleman/moveit_visual_tools), which also has debians. could you do a git pull and make sure you have that dependency installed?

Note: I changed a lot with today's update.

**Comment by JimmyDaSilva** [comment]
I only have one of the 2 errors left now:

[ 75%] Building CXX object ompl_rviz_viewer/CMakeFiles/ompl_rviz_viewer.dir/src/ompl_rviz_viewer.cpp.o
In file included from /home/jimmy/catkin_ws/src/ompl_rviz_viewer/include/ompl_rviz_viewer/ompl_rviz_viewer.h:53:0,
                 from /home/jimmy/catkin_ws/src/ompl_rviz_viewer/src/ompl_rviz_viewer.cpp:40:
/home/jimmy/catkin_ws/src/ompl_rviz_viewer/include/ompl_rviz_viewer/costs/cost_map_2d_optimization_objective.h:46:28: fatal error: ompl/base/Cost.h: No such file or directory
compilation terminated.
make[2]: **\* [ompl_rviz_viewer/CMakeFiles/ompl_rviz_viewer.dir/src/ompl_rviz_viewer.cpp.o] Error 1
make[1]: **\* [ompl_rviz_viewer/CMakeFiles/ompl_rviz_viewer.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

**Comment by davetcoleman** [comment]
Ah your version of ompl is probably too old. What version is it? I'm
testing against source myself.

**Comment by JimmyDaSilva** [comment]
version 0.13.0002516

**Comment by davetcoleman** [comment]
Ah I see, you are using the hydro debian version `ros-hydro-ompl` then, right? It is missing:

> Added new cost infrastructure to plan optimal paths with respect to arbitrary cost functions. Several common cost objective functions have been defined (such as path length and mechanical work) and new ones can easily be defined.

I just checked the [Release Notes](http://ompl.kavrakilab.org/core/releaseNotes.html) and the feature you need was released in OMPL 0.14.0 (December 20, 2013), 3 releases ago. I have no plans on backwards supporting 0.13 I'm afraid, so I think the best solution is to install OMPL from source or perhaps upgrade to ROS Indigo, which has OMPL `0.14.2002850-0`.

@mamoll @isucan any advice?

p.s. I'm pretty sure I'm going to be renaming this repo to `ompl_visual_tools` and releasing it into ROS Indigo in the next month.

**Comment by mamoll** [comment]
Upgrading OMPL seems like the sensible thing to do. You'd probably want to compile MoveIt! from source as well then, if you want to use cost-aware planners in MoveIt!. See http://moveit.ros.org/wiki/OMPL/Add_New_Planner

**Comment by JimmyDaSilva** [comment]
Ok thank you for your help and advice. I will go through this process if 
necessary.
Anyway is ompl 0.14 planned to be updated on ros-hydro ?

**Comment by davetcoleman** [comment]
I have updated the README to reflect these issues. Closing.

**Comment by davetcoleman** [comment]
> Anyway is ompl 0.14 planned to be updated on ros-hydro ?

I do not know.

**Comment by davetcoleman** [comment]
Note: I have just re factored the code to no longer depend on my `lightning_framework` branch, I've renamed the repo to ompl_visual_tools, and I've released it into Indigo. It should be easier to work with now as long as your OMPL version is new enough.

**Comment by gavanderhoorn** [comment]
@davetcoleman wrote:

> It should be easier to work with now as long as your OMPL version is new enough.

Would it perhaps be an idea to formalise this 'new enough' with `version_gt(e)=..` attributes on the `build_depends` tags?

**Comment by davetcoleman** [comment]
yea, ive never used those but that sounds alike a good idea. so would it be:

```
<build_depend version_gte='0.14.0'>
```

?
i need 0.14.0 or newer

**Comment by gavanderhoorn** [comment]
I think you need to use double-quotes, but other than that: that is how I've understood [REP-127](http://www.ros.org/reps/rep-0127.html#build-depend-multiple), yes.

**Comment by davetcoleman** [comment]
Done https://github.com/davetcoleman/ompl_visual_tools/commit/21e2de6d2c5dede3b28b6aaa89abdc240d98d5ae

Thanks for the advice!

**Comment by gavanderhoorn** [comment]
np. Now we only have to wait for the questions on ros answers on why `ompl_visual_tools` won't resolve all its dependencies on Hydro :).
