### ISSUE TITLE
run ompl_visual_tools on Ubuntu 14.04 with ROS indigo

### ISSUE THREAD

**Issue by sherry0009** [davetcoleman/ompl_visual_tools#2]
Hi, I am trying to run ompl_visual_tools on Ubuntu 14.04 with ROS indigo. I have finished the installation by 'sudo apt-get install ros-indigo-ompl-visual-tools'. Then, I try to start Rviz, when I 
type 'roslaunch ompl_visual_tools ompl_rviz.launch', the following error appears:

[ompl_rviz.launch] is neither a launch file in package [ompl_visual_tools] nor is [ompl_visual_tools] a launch file name
The traceback for the exception was written to the log file.

When I type 'rosrun ompl_visual_tools rrt_demo', the following error appears:

[ INFO] [1417664034.185779322]: OMPL Visual Tools Demo ----------------------------------------- 
[ WARN] [1417664035.224539980]: Topic '/ompl_rviz_markers' unable to connect to any subscribers within 1 seconds. It is possible initially published visual messages will be lost.
[ INFO] [1417664035.224644786]: Loading image /opt/ros/indigo/share/ompl_visual_tools/resources/wilbur_medium/wilbur_medium2.ppm
Unable to open file '/opt/ros/indigo/share/ompl_visual_tools/resources/wilbur_medium/wilbur_medium2.ppm'
rrt_demo: /usr/include/boost/thread/pthread/recursive_mutex.hpp:101: boost::recursive_mutex::~recursive_mutex(): Assertion `!pthread_mutex_destroy(&m)' failed.
Aborted (core dumped).

Please tell me how can I resolve it.

Regards.

**Comment by davetcoleman** [comment]
I believe I don't have the correct files being installed in `CMakeLists.txt` - I'm bad about that because I never use debians so don't test it. A quick fix would be to just install it from source. I'd welcome a pull request fix, also

**Comment by sherry0009** [comment]
Thank you for your reply! I am a beginner for ROS, so my question may be stupid. I try to clone source code into my catkin workspace and rebuild. First error disappears. But the second still exists. Indeed, there is no wilbur_medium in resources.

**Comment by davetcoleman** [comment]
I fixed the first problem here:
https://github.com/davetcoleman/ompl_visual_tools/commit/7dcb4ab41c07ed46e1803fb0f1c8acc15e53001e

And I fixed the missing resources here:
https://github.com/davetcoleman/ompl_visual_tools/commit/4cd5d4b371b3eab5b777383ac9e46a2bf8969b9f

I'll re-release the packages to bloom / debian soon. Let me know if this solves your problem.

**Comment by sherry0009** [comment]
Oh, new errors:

[100%] Built target rrt_demo
Install the project...
-- Install configuration: ""
-- Installing: /home/sherry/catkin_ws/install/_setup_util.py
-- Installing: /home/sherry/catkin_ws/install/env.sh
-- Installing: /home/sherry/catkin_ws/install/setup.bash
-- Installing: /home/sherry/catkin_ws/install/setup.sh
-- Installing: /home/sherry/catkin_ws/install/setup.zsh
-- Installing: /home/sherry/catkin_ws/install/.rosinstall
-- Installing: /home/sherry/catkin_ws/install/etc/catkin/profile.d/05.catkin_make.bash
-- Installing: /home/sherry/catkin_ws/install/etc/catkin/profile.d/05.catkin_make_isolated.bash
-- Installing: /home/sherry/catkin_ws/install/lib/pkgconfig/ompl_visual_tools.pc
-- Installing: /home/sherry/catkin_ws/install/share/ompl_visual_tools/cmake/ompl_visual_toolsConfig.cmake
-- Installing: /home/sherry/catkin_ws/install/share/ompl_visual_tools/cmake/ompl_visual_toolsConfig-version.cmake
-- Installing: /home/sherry/catkin_ws/install/share/ompl_visual_tools/package.xml
-- Installing: /home/sherry/catkin_ws/install/lib/libompl_visual_tools_ppm.so
-- Removed runtime path from "/home/sherry/catkin_ws/install/lib/libompl_visual_tools_ppm.so"
-- Installing: /home/sherry/catkin_ws/install/lib/libompl_visual_tools.so
-- Removed runtime path from "/home/sherry/catkin_ws/install/lib/libompl_visual_tools.so"
CMake Error at ompl_visual_tools/cmake_install.cmake:87 (FILE):
  file INSTALL cannot find
  "/home/sherry/catkin_ws/src/ompl_visual_tools/include/$PROJECT_NAME}".
Call Stack (most recent call first):
  cmake_install.cmake:128 (INCLUDE)

make: **\* [install] Error 1
Invoking "make" failed

**Comment by sherry0009** [comment]
I try to add wilbur_medium in old version source code and make. The last error disappears.
But when I input  rosrun ompl_visual_tools rrt_demo, the flowing error appears:

[ INFO] [1418399086.505366134]: OMPL Visual Tools Demo ----------------------------------------- 
[ WARN] [1418399087.549587642]: Topic '/ompl_rviz_markers' unable to connect to any subscribers within 1 seconds. It is possible initially published visual messages will be lost.
[ INFO] [1418399087.549698610]: Loading image /opt/ros/indigo/share/ompl_visual_tools/resources/wilbur_medium/wilbur_medium1.ppm
[ INFO] [1418399087.549950426]: Map Height: 410 Map Width: 410
Debug:   RRT: Planner range detected to be 115.682669
[ INFO] [1418399087.675124960]: Planning 1 out of 1 ------------------------------------
Info:    RRT: Starting planning with 1 states already in datastructure
Info:    ProblemDefinition: Adding approximate solution from planner RRT
Info:    RRT: Created 106731 states
Info:    Solution found in 2.012407 seconds
[ WARN] [1418399089.687749688]: APPROXIMATE solution found
[ERROR] [1418399090.274088427]: Deprecated
[ INFO] [1418399090.481585388]: Shutting down.

**Comment by davetcoleman** [comment]
Ooops, small typo: https://github.com/davetcoleman/ompl_visual_tools/commit/f26eeef88c57a94c36fea18c68d7f14a7ca68202

**Comment by davetcoleman** [comment]
As far as:

> [ WARN] [1418399089.687749688]: APPROXIMATE solution found
> [ERROR] [1418399090.274088427]: Deprecated

Not sure, but no time to test right now

**Comment by sherry0009** [comment]
About small typo f26eeef, maybe
line79  
+install(DIRECTORY include/${PROJECT_NAME}/ DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION})

**Comment by davetcoleman** [comment]
Sorry, I'm getting really sloppy!

**Comment by davetcoleman** [comment]
https://github.com/davetcoleman/ompl_visual_tools/commit/98195160fab28081641dd79224f1d13108b18964

**Comment by sherry0009** [comment]
Thank you! It works.
