### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by boonflies** [davetcoleman/ompl_visual_tools#3]
When I tried to 'catkin_make' the package, 'ompl_visual_tools', I get
the following error.

make[2]: **\* No rule to make target
`/opt/ros/indigo/lib/x86_64-linux-gnu/libompl.so', needed by
`/home/boon/catkin_ws/src/ompl_visual_tools/devel/lib/libompl_visual_tools_ppm.so'.
Stop.
make[1]: **\* [ompl_visual_tools/CMakeFiles/ompl_visual_tools_ppm.dir/all]
Error 2
make: **\* [all] Error 2

Can you help me?

**Comment by davetcoleman** [comment]
Do you have `ros-indigo-ompl` installed with apt-get?

**Comment by davetcoleman** [comment]
I added better instructions:
https://github.com/davetcoleman/ompl_visual_tools/commit/5158ef952b6fc484a72c1ddbbbb794f302f07f38

**Comment by boonflies** [comment]
Earlier, I had installed ompl using apt-get and ompl_viusal_tools was working. But, since I wanted to edit the RRT algorithm, I uninstalled ompl and I installed ompl from source as follows.
1. Create a catkin workspace
2. Clone OMPL into the src/ folder
    $ cd ~/catkin_ws/src
    $ mkdir ompl
    $ cd ompl
    $ mkdir src
    $ cd src
    $ hg clone https://bitbucket.org/ompl/ompl
3. Add the package.xml
    $ cd ~/catkin_ws/src/ompl/src/ompl
    $ wget https://raw.githubusercontent.com/ros-gbp/ompl-release/debian/`rosversion -d`/`lsb_release -cs`/ompl/package.xml
4. Build the packge
    $ cd ~/catkin_ws/src/ompl
    $ catkin_make_isolated

Now, I am not able to build ompl_visual_tools.
I even tried source devel_isolated/setup.bash, before building ompl_visual_tools.

**Comment by davetcoleman** [comment]
Try uninstalling your system version of OMPL? Please let me know if you figure out a solution

**Comment by boonflies** [comment]
I finally got it working. After installing OMPL from source, I copied the files from, "usr/local/lib/x86_64-linux-gnu"(it had ompl libraries) and pasted it in "/opt/ros/indigo/lib/x86_64-linux-gnu" and that solved the problem.

**Comment by davetcoleman** [comment]
woa, sounds like quite the hack

**Comment by alexjung** [comment]
Same problem here. Had installed ompl via the package manager for ros but needed the app functionality. Installed it from source and got this error. Seems like the problem is that FindOMPL.cmake gets the old path of the ros installation which is not there anymore. Hack above worked for me too even if I don't like it.

**Comment by davetcoleman** [comment]
I have to admit something... the kinetic branch of this repo has gotten really sloppy and is very specific to my research. I'm curious if anyone else is finding value out of this repo? I've tried making it integrate better with OMPL but have met resistance, so it has dependencies on a hacked version of OMPL...
