### ISSUE TITLE
Editing RRT algorithm

### ISSUE THREAD

**Issue by boonflies** [davetcoleman/ompl_visual_tools#4]
I have been using ompl_visual_tools for a while. Now, I am trying to
do some modification to the RRT algorithm. But, I could not find the
RRT.cpp file to make the modification that ompl_visual_tools can make
use of.

Should I be manually installing MoveIt to be able to edit the RRT planner?

**Comment by davetcoleman** [comment]
The RRT planner is in the OMPL project, here:
https://github.com/ompl/ompl/blob/master/src/ompl/geometric/planners/rrt/RRT.h
